Repository aemsites/vg-roadchoice-com, pull requests merged in 2024-12, with the labels that each got.

#100 FR: opensearch #69
  blocks/filters/filters.js
  blocks/pagination/pagination.css
  blocks/pagination/pagination.js
  blocks/results-list/product-card.js
  blocks/results-list/results-list.js
  blocks/search/graphql-api.js
  blocks/search/search.js
  constants.json
  scripts/common.js
  templates/search-results/search-results.js
Labels: FR

#102 Release 10
  blocks/dealer-locator/sidebar-maps.js
  blocks/filters/filters.js
  blocks/pagination/pagination.css
  blocks/pagination/pagination.js
  blocks/results-list/product-card.js
  blocks/results-list/results-list.js
  blocks/search/graphql-api.js
  blocks/search/search.js
  constants.json
  package-lock.json
  package.json
  scripts/common.js
  templates/search-results/search-results.js
Labels: Ignore for release

#111 Update aem.js #91
  404.html
  blocks/blog-results/blog-results.js
  blocks/breadcrumb/breadcrumb.js
  blocks/catalogs-table/catalogs-table.js
  blocks/cookies-table/cookies-table.js
  blocks/dealer-locator/dealer-locator.js
  blocks/find-dealer/find-dealer.js
  blocks/footer/footer.js
  blocks/fragment/fragment.js
  blocks/header/header.js
  blocks/hero/hero.js
  blocks/manuals-table/manuals-table.js
  blocks/pdp/pdp.js
  blocks/recommendations/recommendations.js
  blocks/results-list/product-card.js
  blocks/v2-accordion/v2-accordion.js
  blocks/v2-specifications/v2-specifications.js
  constants.json
  head.html
  scripts/aem.js
  scripts/common.js
  scripts/delayed.js
  scripts/lib-franklin.js
  scripts/scripts.js
  templates/blog-article/blog-article.js
  templates/part-category/part-category.js
Labels: FR

#110 add a failsafe if any constants value is missing #97
  blocks/dealer-locator/dealer-locator.js
  blocks/search/graphql-api.js
  blocks/search/search.js
  scripts/common.js
  scripts/delayed.js
Labels: NFR

#112 Release 11
  404.html
  blocks/blog-results/blog-results.js
  blocks/breadcrumb/breadcrumb.js
  blocks/catalogs-table/catalogs-table.js
  blocks/cookies-table/cookies-table.js
  blocks/dealer-locator/dealer-locator.js
  blocks/find-dealer/find-dealer.js
  blocks/footer/footer.js
  blocks/fragment/fragment.js
  blocks/header/header.js
  blocks/hero/hero.js
  blocks/manuals-table/manuals-table.js
  blocks/pdp/pdp.js
  blocks/recommendations/recommendations.js
  blocks/results-list/product-card.js
  blocks/search/graphql-api.js
  blocks/search/search.js
  blocks/v2-accordion/v2-accordion.js
  blocks/v2-specifications/v2-specifications.js
  constants.json
  head.html
  package-lock.json
  package.json
  scripts/aem.js
  scripts/common.js
  scripts/delayed.js
  scripts/lib-franklin.js
  scripts/scripts.js
  templates/blog-article/blog-article.js
  templates/part-category/part-category.js
Labels: Ignore for release
