Repository aemsites/vg-roadchoice-com, pull requests merged in 2024-10, with the labels that each got.

#12 Video implementation in hero #11
  blocks/hero/hero.css
  blocks/hero/hero.js
  icons/pause-video.svg
  icons/play-video.svg
  scripts/video-helper.js
  styles/styles.css
Labels: enhancement, FR

#50 Release 6
  blocks/hero/hero.css
  blocks/hero/hero.js
  icons/pause-video.svg
  icons/play-video.svg
  package-lock.json
  package.json
  scripts/video-helper.js
  styles/styles.css
Labels: Ignore for release

#60 Add multi language logic for the breadcrumbs #58
  README.md
  blocks/breadcrumb/breadcrumb.css
  blocks/breadcrumb/breadcrumb.js
  package.json
Labels: NFR

#67 Multi language content requests #56
  blocks/category-filters/category-filters.js
  blocks/category-pagination/category-pagination.js
  blocks/category-results-list/category-results-list.js
  blocks/columns/columns.js
  blocks/dealer-locator/sidebar-maps.js
  blocks/pdp/pdp.js
  blocks/recommendations/recommendations.js
  blocks/results-list/product-card.js
  blocks/search/search.js
  blocks/search/worker.js
  scripts/common.js
  scripts/scripts.js
  templates/part-category/part-category.js
Labels: NFR

#76 Release 7
  README.md
  blocks/breadcrumb/breadcrumb.css
  blocks/breadcrumb/breadcrumb.js
  blocks/category-filters/category-filters.js
  blocks/category-pagination/category-pagination.js
  blocks/category-results-list/category-results-list.js
  blocks/columns/columns.js
  blocks/dealer-locator/sidebar-maps.js
  blocks/pdp/pdp.js
  blocks/recommendations/recommendations.js
  blocks/results-list/product-card.js
  blocks/search/search.js
  blocks/search/worker.js
  package-lock.json
  package.json
  scripts/common.js
  scripts/scripts.js
  templates/part-category/part-category.js
Labels: Ignore for release

#73 Lint improvements #68
  .editorconfig
  .eslintignore
  .eslintrc.js
  .prettierignore
  blocks/blog-results/blog-results.js
  blocks/cards/cards.js
  blocks/catalogs-table/catalogs-table.js
  blocks/category-filters/category-filters.js
  blocks/category-pagination/category-pagination.js
  blocks/category-results-list/category-results-list.js
  blocks/dealer-locator/dealer-locator.js
  blocks/dealer-locator/vendor/jquery.min.js
  blocks/dealer-locator/vendor/moment-timezone.min.js
  blocks/dealer-locator/vendor/moment.js
  blocks/embed/embed.js
  blocks/filters/filters.js
  blocks/fragment/fragment.js
  blocks/header/header.js
  blocks/hero/hero.js
  blocks/iframe/iframe.js
  blocks/pagination/pagination.js
  blocks/pdp/pdp.js
  blocks/recommendations/recommendations.js
  blocks/results-list/product-card.js
  blocks/results-list/results-list.js
  blocks/search/search.js
  blocks/search/worker.js
  blocks/v2-accordion/v2-accordion.js
  blocks/v2-cards/v2-cards.js
  blocks/v2-embed/v2-embed.js
  blocks/v2-specifications/v2-specifications.js
  eslint.config.mjs
  package-lock.json
  package.json
  prettier.config.mjs
  scripts/common.js
  scripts/delayed.js
  scripts/lib-franklin.js
  scripts/scripts.js
  scripts/video-helper.js
  templates/part-category/part-category.js
  templates/search-results/search-results.js
  tools/sidekick/plugins/authors/authors.js
  tools/sidekick/tools-config.js
Labels: NFR
