Repository aemsites/vg-roadchoice-com, pull requests merged in 2025-05, with the labels that each got.

#161 Release 16
  blocks/v2-custom-form/v2-custom-form.css
  blocks/v2-custom-form/v2-custom-form.js
  package-lock.json
  package.json
Labels: Ignore for release

#164 FR: Form Layout for MCAE - RC #124
  blocks/v2-custom-form/v2-custom-form.css
  styles/styles.css
Labels: FR

#171 Release 17
  404.html
  blocks/fragment/fragment.js
  blocks/v2-custom-form/responses/error.js
  blocks/v2-custom-form/responses/success.js
  blocks/v2-custom-form/v2-custom-form.css
  blocks/v2-custom-form/v2-custom-form.js
  common/custom-dropdown/custom-dropdown.css
  common/custom-dropdown/custom-dropdown.js
  icons/check-thin.svg
  package-lock.json
  package.json
  styles/styles.css
Labels: Ignore for release

#175 Bug: The search query for Bumpers doesn't produce the correct results…
  blocks/pdp/pdp.js
Labels: bug, bugfix
