Repository aemsites/vg-roadchoice-com, pull requests merged in 2025-04, with the labels that each got.

#115 Language setting needs to be applied to all website - RC #114
  scripts/scripts.js
Labels: NFR

#146 FR: Update code to read placeholder.json file #133
  blocks/search/search.js
  placeholder.json
Labels: FR

#147 FR: Add text to the product category pages #144
  templates/part-category/part-category.css
  templates/part-category/part-category.js
Labels: enhancement

#152 Release 15
  blocks/accordion/accordion.css
  blocks/blog-results/blog-results.css
  blocks/carousel/carousel.css
  blocks/catalogs-table/catalogs-table.css
  blocks/category-filters/category-filters.css
  blocks/cookies-table/cookies-table.css
  blocks/dealer-locator/dealer-locator.css
  blocks/filters/filters.css
  blocks/find-dealer/find-dealer.css
  blocks/footer/footer.css
  blocks/fragment/fragment.css
  blocks/header/header.css
  blocks/hero/hero.css
  blocks/iframe/iframe.css
  blocks/media-with-text/media-with-text.css
  blocks/pdp/pdp.css
  blocks/recommendations/recommendations.css
  blocks/results-list/results-list.css
  blocks/search/search.css
  blocks/search/search.js
  blocks/table/table.css
  blocks/v2-accordion/v2-accordion.css
  blocks/v2-custom-form/v2-custom-form.css
  blocks/v2-specifications/v2-specifications.css
  common/custom-dropdown/custom-dropdown.css
  package-lock.json
  package.json
  placeholder.json
  prettier.config.mjs
  scripts/scripts.js
  styles/lazy-styles.css
  styles/styles.css
  templates/part-category/part-category.css
  templates/part-category/part-category.js
  templates/search-results/search-results.css
  tools/sidekick/plugins/authors/authors.css
Labels: Ignore for release

#157 FR: Double Column Variant Form for the MCAE - RC #137
  blocks/v2-custom-form/v2-custom-form.css
  blocks/v2-custom-form/v2-custom-form.js
Labels: FR

#160 FR: Change Base URL of image library #159
  blocks/category-results-list/category-results-list.js
Labels: FR
