Repository aemsites/vg-roadchoice-com, pull requests merged in 2025-10, with the labels that each got.

#283 Bug: Fuzzy search is not working on Canada site #221
  blocks/search/search.js
Labels: bugfix

#284 FR: "Did you mean" feature for search input corrections #205
  blocks/search/autosuggest-helper.js
  blocks/search/search.css
  blocks/search/search.js
Labels: FR

#288 FR: Implement multi-tenancy on the ingestion Lambdas #276
  .github/workflows/publish-notifier.yaml
Labels: FR

#291 Release 24
  blocks/pdp/pdp.js
  blocks/search/autosuggest-helper.js
  blocks/search/search.css
  blocks/search/search.js
  package-lock.json
  package.json
  placeholder.json
  scripts/common.js
  templates/part-category/part-category.js
Labels: Ignore for release
