Repository aemsites/vg-roadchoice-com, pull requests merged in 2025-06, with the labels that each got.

#178 Release 18
  blocks/pdp/pdp.js
  blocks/search/autosuggest-helper.js
  blocks/search/graphql-api.js
  blocks/search/search.css
  blocks/search/search.js
  constants.json
  package-lock.json
  package.json
  placeholder.json
Labels: Ignore for release

#191 Bug: Fixed null issue in search query
  blocks/search/search.js
Labels: bugfix

#194 FR: Updating Button Design #9
  blocks/blog-results/blog-results.css
  blocks/category-filters/category-filters.css
  blocks/footer/footer.css
  blocks/search/search.css
  blocks/v2-custom-form/v2-custom-form.css
  icons/pause-video.svg
  icons/play-video.svg
  styles/styles.css
Labels: FR
