Repository aemsites/vg-roadchoice-com, pull requests merged in 2025-07, with the labels that each got.

#218 Release 20
  blocks/iframe/iframe.css
  blocks/iframe/iframe.js
  blocks/pdp/pdp.js
  blocks/search/search.js
  package.json
Labels: Ignore for release

#232 NFR: Update the breadcrumbs to show a maximum amount to prevent scrolling #22
  blocks/breadcrumb/breadcrumb.css
Labels: NFR

#239 Bug: No product description displayed after clicking search result #237
  blocks/results-list/product-card.js
Labels: bugfix
